[build-system]
requires = ["setuptools",
            "wheel",
            "numpy",
            "cython"]
#            "cython@git+https://github.com/cython/cython"]
build-backend = 'setuptools.build_meta'
