name: CI

on:
  push:
  pull_request:

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: py39-test
        - macos: py310-test
        - windows: py311-test
